package com.altimetrik.wallet.walrew.exception;

public class WalletException extends Exception {

	private static final long serialVersionUID = 2606486540640140662L;
	private WalletError error;

	public WalletException(WalletError error) {
		this.error = error;
	}

	public WalletException(WalletError error, Exception cause) {
		super(error.message);
		this.error = error;
		this.initCause(cause);
	}

	public String getErrorMessage() {
		return error.message;
	}


	public enum WalletError {
		
		AUTHORIZATION_FAILED_20000("AUTHORIZATION_FAILED", "Client does not have permission to invoke service for Wallet.", "Business partner must be configured to send transactions for Wallet."),
		AUTHORIZATION_FAILED_20001("AUTHORIZATION_FAILED", "Client does not have permission to invoke the service.", "Business partner must be configured to send transactions for Wallet."),
		CRITICAL_ERROR_40001("CRITICAL_ERROR", "Received critical error during processing. Manual intervention is advised.", "Received critical error during processing. Manual intervention is advised."),
		CRITICAL_ERROR_40002("CRITICAL_ERROR", "Received critical error during reversal processing. Manual intervention is advised.", "Received critical error during reversal processing. Manual intervention is advised."),
		INVALID_INPUT_FORMAT_60000("INVALID_INPUT_FORMAT", "Unsupported record type specified.", "Record Type specified in the detail record must be one of the recognized record types."),
		INVALID_INPUT_FORMAT_60001("INVALID_INPUT_FORMAT", "Unsupported version for record type.", "The Version specified in the record must be a supported record version for the record type."),
		INVALID_INPUT_FORMAT_60002("INVALID_INPUT_FORMAT", "File Date must be numeric.", "File Date must contain digits 0-9"),
		INVALID_INPUT_FORMAT_60003("INVALID_INPUT_FORMAT", "File Header must be first record in file.", "The File Header record is required and must be the first record in the file. Only one File Header record is allowed."),
		INVALID_INPUT_FORMAT_60004("INVALID_INPUT_FORMAT", "File Number must be numeric.", "File Number must contain digits 0-9"),
		INVALID_INPUT_FORMAT_60005("INVALID_INPUT_FORMAT", "File Time must be numeric.", "File time must contain digits 0-9"),
		INVALID_INPUT_FORMAT_60006("INVALID_INPUT_FORMAT", "File Trailer must be last record in file.", "The File Trailer record is required and must be the last record in the file. Only one File Trailer record is allowed."),
		INVALID_INPUT_FORMAT_60007("INVALID_INPUT_FORMAT", "Mapping Id must be numeric.", "Mapping Id"),
		INVALID_INPUT_FORMAT_60008("INVALID_INPUT_FORMAT", "Record Count in File Trailer is not numeric.", "Record Count must contain digits 0-9"),
		INVALID_INPUT_FORMAT_60100("INVALID_INPUT_FORMAT", "Originator Reference must be numeric.", "Originator Reference"),
		INVALID_INPUT_FORMAT_60101("INVALID_INPUT_FORMAT", "Wallet must be numeric.", "Wallet must contain digits 0-9"),
		INVALID_INPUT_FORMAT_60102("INVALID_INPUT_FORMAT", "Transfer Transaction Reference must be numeric.", "Transfer Transaction Reference"),
		INVALID_INPUT_FORMAT_60103("INVALID_INPUT_FORMAT", "Account Number must be numeric and valid.", "Account Number is numeric"),
		INVALID_INPUT_FORMAT_60104("INVALID_INPUT_FORMAT", "Amount must be numeric and valid.", "Amount is numeric"),
		INVALID_INPUT_FORMAT_60105("INVALID_INPUT_FORMAT", "Currency code must be numeric.", "Currency Code is numeric"),
		INVALID_INPUT_FORMAT_60106("INVALID_INPUT_FORMAT", "Local Date must be numeric.", "Local Date is numeric"),
		INVALID_INPUT_FORMAT_60107("INVALID_INPUT_FORMAT", "Local Time must be numeric.", "Local Time is numeric"),
		INVALID_INPUT_FORMAT_60108("INVALID_INPUT_FORMAT", "Processor ID must be numeric.", "Processor ID is numeric"),
		INVALID_INPUT_FORMAT_60109("INVALID_INPUT_FORMAT", "Routing and Transit Number must be numeric.", "Routing & Transit Number is numeric"),
		INVALID_INPUT_FORMAT_60110("INVALID_INPUT_FORMAT", "Expiry Date must be numeric.", "Expiry Date is numeric"),
		INVALID_INPUT_FORMAT_60111("INVALID_INPUT_FORMAT", "Unsupported version for File Header record.", "Unsupported version for File Header record."),
		INVALID_INPUT_FORMAT_60112("INVALID_INPUT_FORMAT", "Date of Birth must be numeric.", "Date of Birth is numeric"),
		INVALID_INPUT_FORMAT_60113("INVALID_INPUT_FORMAT", "Unsupported version for File Trailer record.", "Unsupported version for File Trailer record."),
		INVALID_INPUT_FORMAT_60114("INVALID_INPUT_FORMAT", "File contains no detail records.", "File contains no detail records."),
		INVALID_INPUT_FORMAT_60115("INVALID_INPUT_FORMAT", "Version must be numeric.", "Version must be numeric."),
		INVALID_INPUT_FORMAT_60116("INVALID_INPUT_FORMAT", "Social Network ID must valid.", "Social Network ID must valid."),
		INVALID_INPUT_FORMAT_60117("INVALID_INPUT_FORMAT", "Original Request ID must 1 to 20 digits.", "Original Request ID must 1 to 20 digits."),
		INVALID_INPUT_FORMAT_60118("INVALID_INPUT_FORMAT", "Routing and Transit must be numeric.", "Routing and Transit must be numeric."),
		INVALID_INPUT_FORMAT_60119("INVALID_INPUT_FORMAT", "Local Date must be in the format of MMdd.", "Local Date must be in the format of MMdd."),
		INVALID_INPUT_FORMAT_60120("INVALID_INPUT_FORMAT", "Local Time must be the format of HHmmss.", "Local Time must be the format of HHmmss."),
		INVALID_INPUT_FORMAT_60121("INVALID_INPUT_FORMAT", "Default Indicator must be 'T' or 'F'.", "Default Indicator must be 'T' or 'F'."),
		INVALID_INPUT_FORMAT_60122("INVALID_INPUT_FORMAT", "Country subdivision must be an alpha character.", "Country subdivision must be an alpha character."),
		INVALID_INPUT_FORMAT_60123("INVALID_INPUT_FORMAT", "Middle name must be numeric or alpha.", "Middle name must be numeric or alpha."),
		INVALID_INPUT_FORMAT_60124("INVALID_INPUT_FORMAT", "Street Address Line 1 must valid.", "Street Address Line 1 must valid."),
		INVALID_INPUT_FORMAT_60125("INVALID_INPUT_FORMAT", "Street Address Line 2 must valid.", "Street Address Line 2 must valid."),
		INVALID_INPUT_FORMAT_60126("INVALID_INPUT_FORMAT", "City must be valid.", "City must be valid."),
		INVALID_INPUT_FORMAT_60127("INVALID_INPUT_FORMAT", "State/Province must be valid.", "State/Province must be valid."),
		INVALID_INPUT_FORMAT_60128("INVALID_INPUT_FORMAT", "Postal Code must be Alpha Numeric.", "Postal Code must be Alpha Numeric."),
		INVALID_INPUT_FORMAT_60129("INVALID_INPUT_FORMAT", "Cardholder First Name must be valid", "Cardholder First Name must be valid"),
		INVALID_INPUT_FORMAT_60130("INVALID_INPUT_FORMAT", "Cardholder Last Name must be valid", "Cardholder Last Name must be valid"),
		INVALID_INPUT_FORMAT_60131("INVALID_INPUT_FORMAT", "Response Data Flag must be numeric and the value range must be between 0 and 3.", "Response Data Flag must be numeric and the value range must be between 0 and 3."),
		INVALID_INPUT_FORMAT_60132("INVALID_INPUT_FORMAT", "Card Acceptor State/Province Code must be 2 or 3 characters.", "Card Acceptor State/Province Code must be 2 or 3 characters."),
		INVALID_INPUT_FORMAT_60133("INVALID_INPUT_FORMAT", "Card Acceptor Country must be a valid alpha country code.", "Card Acceptor Country must be a valid alpha country code."),
		INVALID_INPUT_FORMAT_60134("INVALID_INPUT_FORMAT", "Card Number must be numeric and valid.", "Card Number must be numeric and valid."),
		INVALID_INPUT_FORMAT_60135("INVALID_INPUT_FORMAT", "Amount Value must be numeric.", "Amount Value must be numeric."),
		INVALID_INPUT_FORMAT_60136("INVALID_INPUT_FORMAT", "Amount Currency must be valid numeric currency code.", "Amount Currency must be valid numeric currency code."),
		INVALID_INPUT_FORMAT_60137("INVALID_INPUT_FORMAT", "Mapping Id must be numeric", "Mapping Id must be numeric"),
		INVALID_INPUT_FORMAT_60138("INVALID_INPUT_FORMAT", "Receiving Card Number must be numeric and valid.", "Receiving Card Number must be numeric and valid."),
		INVALID_INPUT_FORMAT_60139("INVALID_INPUT_FORMAT", "Expiry Year must be numeric and valid.", "Expiry Year must be numeric and valid."),
		INVALID_INPUT_FORMAT_60140("INVALID_INPUT_FORMAT", "Expiry Month must be numeric and valid.", "Expiry Month must be numeric and valid."),
		INVALID_INPUT_FORMAT_60141("INVALID_INPUT_FORMAT", "Funding Card Number must be numeric and valid.", "Funding Card Number must be numeric and valid."),
		INVALID_INPUT_FORMAT_60142("INVALID_INPUT_FORMAT", "Failed to create request.", "Failed to create request."),
		INVALID_INPUT_FORMAT_60143("INVALID_INPUT_FORMAT", "Card Acceptor Name must be Alpha Characters.", "Card Acceptor Name must be Alpha Characters."),
		INVALID_INPUT_FORMAT_60144("INVALID_INPUT_FORMAT", "Card Acceptor City must be Alpha Characters.", "Card Acceptor City must be Alpha Characters."),
		INVALID_INPUT_FORMAT_60145("INVALID_INPUT_FORMAT", "Card Acceptor Postal Code must be in proper format.", "Card Acceptor Postal Code must be in proper format."),
		INVALID_INPUT_FORMAT_60147("INVALID_INPUT_FORMAT", "Transaction Reference must be Numeric.", "Transaction Reference must be Numeric."),
		INVALID_INPUT_FORMAT_60149("INVALID_INPUT_FORMAT", "Merchant ID must be Alpha Numeric.", "Merchant ID must be Alpha Numeric."),
		INVALID_INPUT_FORMAT_60150("INVALID_INPUT_FORMAT", "PIN Block must be in Hexadicmal format.", "PIN Block must be in Hexadicmal format."),
		INVALID_INPUT_FORMAT_60151("INVALID_INPUT_FORMAT", "Invalid Channel.", "Invalid Channel."),
		INVALID_INPUT_FORMAT_60152("INVALID_INPUT_FORMAT", "Receiver Track 2 Data must be in proper format.Receiver Track 2 Data must be in proper format.", ""),
		INVALID_INPUT_FORMAT_60153("INVALID_INPUT_FORMAT", "Card Sequence Number must be a number.", "Card Sequence Number must be a number."),
		INVALID_INPUT_FORMAT_60154("INVALID_INPUT_FORMAT", "EMV Data must be a string.", "EMV Data must be a string."),
		INVALID_INPUT_FORMAT_60155("INVALID_INPUT_FORMAT", "Invalid Account Type.", "Invalid Account Type."),
		INVALID_INPUT_FORMAT_60156("INVALID_INPUT_FORMAT", "CardAcceptor Terminal Indentifier must be a String.", "CardAcceptor Terminal Indentifier must be a String."),
		INVALID_INPUT_FORMAT_60157("INVALID_INPUT_FORMAT", "Invalid Payment POS Entry Mode.", "Invalid Payment POS Entry Mode."),
		INVALID_INPUT_FORMAT_60158("INVALID_INPUT_FORMAT", "Invalid Card Presence Indicator.", "Invalid Card Presence Indicator."),
		INVALID_INPUT_FORMAT_60159("INVALID_INPUT_FORMAT", "Reversal Reason must be Alpha Numeric.", "Reversal Reason must be Alpha Numeric."),
		INVALID_INPUT_FORMAT_60161("INVALID_INPUT_FORMAT", "Invalid Channel.", "Invalid Channel."),
		INVALID_INPUT_FORMAT_60162("INVALID_INPUT_FORMAT", "Additional Information must be Alpha Numeric.", "Additional Information must be Alpha Numeric."),
		INVALID_INPUT_FORMAT_60163("INVALID_INPUT_FORMAT", "First Name must be valid.", "First Name must be valid."),
		INVALID_INPUT_FORMAT_60164("INVALID_INPUT_FORMAT", "Last Name must be valid.", "Last Name must be valid."),
		INVALID_INPUT_FORMAT_60165("INVALID_INPUT_FORMAT", "Country Code is Invalid.", "Country Code is Invalid."),
		INVALID_INPUT_FORMAT_60166("INVALID_INPUT_FORMAT", "Phone Number must be numeric.", "Phone Number must be numeric."),
		INVALID_INPUT_FORMAT_60167("INVALID_INPUT_FORMAT", "Funding Card Assigned ID must be numeric.", "Funding Card Assigned ID must be numeric."),
		INVALID_INPUT_FORMAT_60168("INVALID_INPUT_FORMAT", "Payment Pos Entry Mode must be numeric.", "Payment Pos Entry Mode must be numeric."),
		INVALID_INPUT_FORMAT_60169("INVALID_INPUT_FORMAT", "Card Sequence Number must be numeric.", "Card Sequence Number must be numeric."),
		INVALID_INPUT_FORMAT_60170("INVALID_INPUT_FORMAT", "POS Card Data Terminal Input Capability Indicator must be numeric.", "POS Card Data Terminal Input Capability Indicator must be numeric."),
		INVALID_INPUT_FORMAT_60171("INVALID_INPUT_FORMAT", "Payment Initiation Channel must be numeric.", "Payment Initiation Channel must be numeric."),
		INVALID_INPUT_FORMAT_60172("INVALID_INPUT_FORMAT", "Transaction Fee value must be numeric.", "Transaction Fee value must be numeric."),
		INVALID_INPUT_FORMAT_60173("INVALID_INPUT_FORMAT", "Transaction Fee Currency Code must be numeric.", "Transaction Fee Currency Code must be numeric."),
		INVALID_INPUT_FORMAT_60174("INVALID_INPUT_FORMAT", "Additional Sender Information should be Check or Cash.", "Additional Sender Information should be Check or Cash."),
		INVALID_INPUT_FORMAT_60175("INVALID_INPUT_FORMAT", "Invalid Additional Sender Information.", "Invalid Additional Sender Information."),
		INVALID_INPUT_FORMAT_60182("INVALID_INPUT_FORMAT", "Sender Phone Number must be numeric.", "Sender Phone Number must be numeric."),
		INVALID_INPUT_FORMAT_60183("INVALID_INPUT_FORMAT", "Receiver Phone Number must be numeric.", "Receiver Phone Number must be numeric."),
		INVALID_INPUT_FORMAT_60185("INVALID_INPUT_FORMAT", "Receiver First Name cannot be all numeric.", "Receiver First Name cannot be all numeric."),
		INVALID_INPUT_FORMAT_60186("INVALID_INPUT_FORMAT", "Receiver Last Name cannot be all numeric.", "Receiver Last Name cannot be all numeric."),
		INVALID_INPUT_FORMAT_60187("INVALID_INPUT_FORMAT", "Sender FundingCard AccountNumber must be numeric.", "Sender FundingCard AccountNumber must be numeric."),
		INVALID_INPUT_FORMAT_60188("INVALID_INPUT_FORMAT", "Sender First Name cannot be all numeric.", "Sender First Name cannot be all numeric."),
		INVALID_INPUT_FORMAT_60189("INVALID_INPUT_FORMAT", "Sender Last Name cannot be all numeric.", "Sender Last Name cannot be all numeric."),
		INVALID_INPUT_FORMAT_60190("INVALID_INPUT_FORMAT", "Transaction Amount Value must be numeric.", "Transaction Amount Value must be numeric."),
		INVALID_INPUT_FORMAT_60191("INVALID_INPUT_FORMAT", "Transaction Amount Currency must be valid numeric currency code.", "Transaction Amount Currency must be valid numeric currency code."),
		INVALID_INPUT_FORMAT_60192("INVALID_INPUT_FORMAT", "Sender Date of Birth must be a valid date in the format MMDDYYYY.", "Sender Date of Birth must be a valid date in the format MMDDYYYY."),
		INVALID_INPUT_FORMAT_60193("INVALID_INPUT_FORMAT", "Receiver Date of Birth must be a valid date in the format MMDDYYYY.", "Receiver Date of Birth must be a valid date in the format MMDDYYYY."),
		INVALID_INPUT_FORMAT_60194("INVALID_INPUT_FORMAT", "User name or Mobile Number is invalid", "User name or Mobile Number is invalid"),
		INVALID_INPUT_FORMAT_60195("INVALID_INPUT_FORMAT", "Unable to generate OTP", "Unable to generate OTP, Please retry after sometime"),
		INVALID_INPUT_FORMAT_60196("INVALID_INPUT_FORMAT", "Unknown Card Type or Network Type. Currently accepted cards are Master Card, Visa, DISCOVER & AMEX", "Unknown Card Type or Network Type. Currently accepted cards are Master Card, Visa, DISCOVER & AMEX"),
		INVALID_INPUT_FORMAT_60197("INVALID_INPUT_FORMAT", "Invalid Card Number", "Invalid Card Number"),
		INVALID_INPUT_FORMAT_60198("INVALID_INPUT_FORMAT", "User Name already exists", "User Name already exists"),
		INVALID_INPUT_FORMAT_60199("INVALID_INPUT_FORMAT", "Mobile Number already exists", "Mobile Number already exists"),
		INVALID_INPUT_FORMAT_60200("INVALID_INPUT_FORMAT", "Username not exists", "Username not exists"),
		INVALID_INPUT_FORMAT_60201("INVALID_INPUT_FORMAT", "Invalid Wallet Name", "Invalid Wallet Name"),
		INVALID_INPUT_FORMAT_60202("INVALID_INPUT_FORMAT", "Insufficient Funds", "Insufficient Funds"),
		INVALID_INPUT_FORMAT_60203("INVALID_INPUT_FORMAT", "Top Up amount is not Sufficient to buy this product", "Top Up amount is not Sufficient to buy this product"),

		INVALID_INPUT_LENGTH_70001("INVALID_INPUT_LENGTH", "Subscriber Id must be within correct range for subscriber type", "Subscriber Id is invalid length"),
		INVALID_INPUT_LENGTH_70002("INVALID_INPUT_LENGTH", "Cardholder First Name must be 1 to 25 characters in length.", "Cardholder First Name must be 1 to 25 characters in length."),
		INVALID_INPUT_LENGTH_70003("INVALID_INPUT_LENGTH", "Cardholder Last Name must be 1 to 35 characters in length.", "Cardholder Last Name must be 1 to 35 characters in length."),
		INVALID_INPUT_LENGTH_70004("INVALID_INPUT_LENGTH", "Street Address Line 1 must be 1 to 50 characters in length.", "Street Address Line 1 must be 1 to 50 characters in length."),
		INVALID_INPUT_LENGTH_70005("INVALID_INPUT_LENGTH", "City must be 1 to 20 characters in length.", "City must be 1 to 20 characters in length."),
		INVALID_INPUT_LENGTH_70006("INVALID_INPUT_LENGTH", "State/Province must be 2 to 3 characters in length.", "State/Province must be 2 to 3 characters in length."),
		INVALID_INPUT_LENGTH_70007("INVALID_INPUT_LENGTH", "Country Code must be 3 characters in length.", "Country Code must be 3 characters in length."),
		INVALID_INPUT_LENGTH_70008("INVALID_INPUT_LENGTH", "Expiry Date must be 6 digits in length.", "Expiry Date must be 6 digits in length."),
		INVALID_INPUT_LENGTH_70009("INVALID_INPUT_LENGTH", "Alias must be 1 to 20 characters in length.", "Alias must be 1 to 20 characters in length."),
		INVALID_INPUT_LENGTH_70010("INVALID_INPUT_LENGTH", "Sender Name must be 1 to 24 characters in length.", "Sender Name must be 1 to 24 characters in length."),
		INVALID_INPUT_LENGTH_70011("INVALID_INPUT_LENGTH", "Receiver Name must be 1 to 24 characters in length.", "Receiver Name must be 1 to 24 characters in length."),
		INVALID_INPUT_LENGTH_70012("INVALID_INPUT_LENGTH", "Receiver Name must be 1 to 24 characters in length.", "Receiver Name must be 1 to 24 characters in length."),
		INVALID_INPUT_LENGTH_70013("INVALID_INPUT_LENGTH", "Transaction Reference must be 19 characters in length.", "Transaction Reference must be 19 characters in length."),
		INVALID_INPUT_LENGTH_70014("INVALID_INPUT_LENGTH", "Reversal Reason must be 1 to 50 characters in length.", "Reversal Reason must be 1 to 50 characters in length."),
		INVALID_INPUT_LENGTH_70015("INVALID_INPUT_LENGTH", "Processor ID must be 10 in length.", "Processor ID must be 10 in length."),
		INVALID_INPUT_LENGTH_70016("INVALID_INPUT_LENGTH", "Routing and Transit Number must be 9 in length.", "Routing and Transit Number must be 9 in length."),
		INVALID_INPUT_LENGTH_70017("INVALID_INPUT_LENGTH", "Local Date must be 4 digits in length.", "Local Date must be 4 digits in length."),
		INVALID_INPUT_LENGTH_70018("INVALID_INPUT_LENGTH", "Local Time must be 6 digits in length.", "Local Time must be 6 digits in length."),
		INVALID_INPUT_LENGTH_70019("INVALID_INPUT_LENGTH", "Cardholder Middle Name must be 1 character in length.", "Cardholder Middle Name must be 1 character in length."),
		INVALID_INPUT_LENGTH_70020("INVALID_INPUT_LENGTH", "Postal Code must be 1 to 10 characters in length.", "Postal Code must be 1 to 10 characters in length."),
		INVALID_INPUT_LENGTH_70021("INVALID_INPUT_LENGTH", "Wallet must be between 4 and 6 digits in length.", "Wallet must be between 4 and 6 digits in length."),
		INVALID_INPUT_LENGTH_70022("INVALID_INPUT_LENGTH", "Street Address Line 2 must be 1 to 50 characters in length.", "Street Address Line 2 must be 1 to 50 characters in length."),
		INVALID_INPUT_LENGTH_70023("INVALID_INPUT_LENGTH", "Street Address Line 1 must be 1 to 50 characters in length", "Street Address Line 1 must be 1 to 50 characters in length"),
		INVALID_INPUT_LENGTH_70024("INVALID_INPUT_LENGTH", "Street Address Line 2 must be 1 to 50 characters in length.", "Street Address Line 2 must be 1 to 50 characters in length."),
		INVALID_INPUT_LENGTH_70025("INVALID_INPUT_LENGTH", "City must be 1 to 25 characters in length.", "City must be 1 to 25 characters in length."),
		INVALID_INPUT_LENGTH_70026("INVALID_INPUT_LENGTH", "State/Province must be 2 or 3 characters in length.", "State/Province must be 2 or 3 characters in length."),
		INVALID_INPUT_LENGTH_70027("INVALID_INPUT_LENGTH", "Postal Code must be 1 to 10 characters in length", "Postal Code must be 1 to 10 characters in length."),
		INVALID_INPUT_LENGTH_70028("INVALID_INPUT_LENGTH", "Country Code must be 3 characters in length.", "Country Code must be 3 characters in length."),
		INVALID_INPUT_FORMAT_70029("INVALID_INPUT_FORMAT", "Country Code must be a valid alpha country code.", "Country Code must be a valid alpha country code."),
		INVALID_INPUT_LENGTH_70030("INVALID_INPUT_LENGTH", "Response Data Flag must be 1 digit.", "Response Data Flag must be 1 digit."),
		INVALID_INPUT_LENGTH_70031("INVALID_INPUT_LENGTH", "Card Acceptor Name must be 1 to 22 characters in length.", "Card Acceptor Name must be 1 to 22 characters in length."),
		INVALID_INPUT_LENGTH_70032("INVALID_INPUT_LENGTH", "Client Code must be 1 to 250 characters in length.", "Client Code must be 1 to 250 characters in length."),
		INVALID_INPUT_LENGTH_70033("INVALID_INPUT_LENGTH", "Merchant Type must be 4 digits in length.", "Merchant Type must be 4 digits in length."),
		INVALID_INPUT_LENGTH_70034("INVALID_INPUT_LENGTH", "Merchant Type must be 4 digits.", "Merchant Type must be 4 digits."),
		INVALID_INPUT_LENGTH_70035("INVALID_INPUT_LENGTH", "Card Acceptor City must be 1 to 13 characters in length.", "Card Acceptor City must be 1 to 13 characters in length."),
		INVALID_INPUT_LENGTH_70036("INVALID_INPUT_LENGTH", "Card Acceptor State/Province Code must be 2 or 3 characters in length.", "Card Acceptor State/Province Code must be 2 or 3 characters in length."),
		INVALID_INPUT_LENGTH_70037("INVALID_INPUT_LENGTH", "Card Acceptor Country must be 3 alpha characters in length.", "Card Acceptor Country must be 3 alpha characters in length."),
		INVALID_INPUT_LENGTH_70038("INVALID_INPUT_LENGTH", "Card Acceptor Postal Code must be 1 to 10 in length.", "Card Acceptor Postal Code must be 1 to 10 in length."),
		INVALID_INPUT_LENGTH_70039("INVALID_INPUT_LENGTH", "Card Number must be 11 to 19 characters in length.", "Card Number must be 11 to 19 characters in length."),
		INVALID_INPUT_LENGTH_70040("INVALID_INPUT_LENGTH", "Amount Value must be between 2 and 12 characters in length.", "Amount Value must be between 2 and 12 characters in length."),
		INVALID_INPUT_LENGTH_70041("INVALID_INPUT_LENGTH", "Amount Currency must be 3 digits in length.", "Amount Currency must be 3 digits in length."),
		INVALID_INPUT_LENGTH_70042("INVALID_INPUT_LENGTH", "Funding Card Assigned ID must be 6 characters in length.", "Funding Card Assigned ID must be 6 characters in length."),
		INVALID_INPUT_LENGTH_70043("INVALID_INPUT_LENGTH", "Funding UCAF must be 1 to 32 characters in length.", "Funding UCAF must be 1 to 32 characters in length."),
		INVALID_INPUT_LENGTH_70044("INVALID_INPUT_LENGTH", "Receiving Subscriber Alias must be 1 to 20 characters in length.", "Receiving Subscriber Alias must be 1 to 20 characters in length."),
		INVALID_INPUT_LENGTH_70045("INVALID_INPUT_LENGTH", "Receiving Subscriber ID must be 1 to 99 characters in length.", "Receiving Subscriber ID must be 1 to 99 characters in length."),
		INVALID_INPUT_LENGTH_70046("INVALID_INPUT_LENGTH", "Receiving Card Number must be 11 to 19 characters in length.", "Receiving Card Number must be 11 to 19 characters in length."),
		INVALID_INPUT_LENGTH_70047("INVALID_INPUT_LENGTH", "Phone Number must be 1 to 20 characters in length", "Phone Number must be 1 to 20 characters in length"),
		INVALID_INPUT_LENGTH_70048("INVALID_INPUT_LENGTH", "Funding Subscriber Alias must be 1 to 20 characters in length.", "Funding Subscriber Alias must be 1 to 20 characters in length."),
		INVALID_INPUT_LENGTH_70049("INVALID_INPUT_LENGTH", "Funding Subscriber ID must be 1 to 99 characters in length.", "Funding Subscriber ID must be 1 to 99 characters in length."),
		INVALID_INPUT_LENGTH_70050("INVALID_INPUT_LENGTH", "Expiry Year must be 4 digits in length.", "Expiry Year must be 4 digits in length."),
		INVALID_INPUT_LENGTH_70051("INVALID_INPUT_LENGTH", "Expiry Month must be 2 digits in length.", "Expiry Month must be 2 digits in length."),
		INVALID_INPUT_LENGTH_70052("INVALID_INPUT_LENGTH", "Funding Card Number must be 11 to 19 characters in length.", "Funding Card Number must be 11 to 19 characters in length."),
		INVALID_INPUT_LENGTH_70053("INVALID_INPUT_LENGTH", "Client Code must be 1 to 250 characters in length.", "Client Code must be 1 to 250 characters in length."),
		INVALID_INPUT_LENGTH_70054("INVALID_INPUT_LENGTH", "Mapping Id is not the correct length", "Mapping Id is not the correct length"),
		INVALID_INPUT_LENGTH_70055("INVALID_INPUT_LENGTH", "Cardholder Name must be 1 to 24 characters in length.", "Cardholder Name must be 1 to 24 characters in length."),
		INVALID_INPUT_LENGTH_70057("INVALID_INPUT_LENGTH", "Merchant ID must be within correct range for Merchant ID.", "Merchant ID must be within correct range for Merchant ID."),
		INVALID_INPUT_LENGTH_70058("INVALID_INPUT_LENGTH", "PIN Block must be within correct range for PIN Block.", "PIN Block must be within correct range for PIN Block."),
		INVALID_INPUT_LENGTH_70168("INVALID_INPUT_LENGTH", "Sender First Name must be 1 to 35 in length.", "Sender First Name must be 1 to 35 in length."),
		INVALID_INPUT_LENGTH_70169("INVALID_INPUT_LENGTH", "Sender Middle Name must be 1 in length.", "Sender Middle Name must be 1 in length."),
		INVALID_INPUT_LENGTH_70170("INVALID_INPUT_LENGTH", "Sender Last Name must be 1 to 35 in length.", "Sender Last Name must be 1 to 35 in length."),
		INVALID_INPUT_LENGTH_70171("INVALID_INPUT_LENGTH", "Receiver First Name must be 1 to 35 in length.", "Receiver First Name must be 1 to 35 in length."),
		INVALID_INPUT_LENGTH_70172("INVALID_INPUT_LENGTH", "Receiver Middle Name must be 1 in length.", "Receiver Middle Name must be 1 in length."),
		INVALID_INPUT_LENGTH_70173("INVALID_INPUT_LENGTH", "Receiver Last Name must be 1 to 35 in length.", "Receiver Last Name must be 1 to 35 in length."),
		INVALID_INPUT_LENGTH_70174("INVALID_INPUT_LENGTH", "Sender Date of Birth must be 8 in length.", "Sender Date of Birth must be 8 in length."),
		INVALID_INPUT_LENGTH_70175("INVALID_INPUT_LENGTH", "Receiver Date of Birth must be 8 in length.", "Receiver Date of Birth must be 8 in length."),
		INVALID_INPUT_LENGTH_70176("INVALID_INPUT_LENGTH", "Sender phone number must be 1 to 20 in length.", "Sender phone number must be 1 to 20 in length."),
		INVALID_INPUT_LENGTH_70177("INVALID_INPUT_LENGTH", "Receiver phone number must be 1 to 20 characters in length.", "Receiver phone number must be 1 to 20 characters in length."),
		INVALID_INPUT_LENGTH_70178("INVALID_INPUT_LENGTH", "Additional Message must be 1 to 65 in length.", "Additional Message must be 1 to 65 in length."),
		INVALID_INPUT_LENGTH_70179("INVALID_INPUT_LENGTH", "Language Identification must be 1 to 3 in length.", "Language Identification must be 1 to 3 in length."),
		INVALID_INPUT_LENGTH_70180("INVALID_INPUT_LENGTH", "Language Data must be 1 to 50 in length.", "Language Data must be 1 to 50 in length"),
		INVALID_INPUT_LENGTH_70181("INVALID_INPUT_LENGTH", "Participation ID must be 1 to 30 in length.", "Participation ID must be 1 to 30 in length."),
		INVALID_INPUT_LENGTH_70182("INVALID_INPUT_LENGTH", "Receiving Account Number must be 1 to 20 in length.", "Receiving Account Number must be 1 to 20 in length."),
		INVALID_INPUT_LENGTH_70183("INVALID_INPUT_LENGTH", "Sender Address Line 1 must be 1 to 50 in length.", "Sender Address Line 1 must be 1 to 50 in length."),
		INVALID_INPUT_LENGTH_70184("INVALID_INPUT_LENGTH", "Sender Address City must be 1 to 25 in length.", "Sender Address City must be 1 to 25 in length."),
		INVALID_INPUT_LENGTH_70185("INVALID_INPUT_LENGTH", "Sender Address Postal Code must be 1 to 10 in length.", "Sender Address Postal Code must be 1 to 10 in length."),
		INVALID_INPUT_LENGTH_70186("INVALID_INPUT_LENGTH", "Sender Address Country Code must be 3 in length.", "Sender Address Country Code must be 3 in length."),
		INVALID_INPUT_LENGTH_70187("INVALID_INPUT_LENGTH", "Sender Address Country Subdivision must be 1 to 3 in length.", "Sender Address Country Subdivision must be 1 to 3 in length."),
		INVALID_INPUT_LENGTH_70188("INVALID_INPUT_LENGTH", "Receiver Address Line 1 must be 1 to 50 in length.", "Receiver Address Line 1 must be 1 to 50 in length."),
		INVALID_INPUT_LENGTH_70189("INVALID_INPUT_LENGTH", "Receiver Address City must be 1 to 25 in length.", "Receiver Address City must be 1 to 25 in length."),
		INVALID_INPUT_LENGTH_70190("INVALID_INPUT_LENGTH", "Receiver Address Postal Code must be 1 to 10 in length.", "Receiver Address Postal Code must be 1 to 10 in length."),
		INVALID_INPUT_LENGTH_70191("INVALID_INPUT_LENGTH", "Receiver Address Country Code must be 3 in length.", "Receiver Address Country Code must be 3 in length."),
		INVALID_INPUT_LENGTH_70192("INVALID_INPUT_LENGTH", "Receiver Address Country Subdivision must be 1 to 3 in length.", "Receiver Address Country Subdivision must be 1 to 3 in length."),
		INVALID_INPUT_LENGTH_70193("INVALID_INPUT_LENGTH", "Sender FundingCard AccountNumber must be 1 to 20 in length.", "Sender FundingCard AccountNumber must be 1 to 20 in length."),
		INVALID_INPUT_LENGTH_70194("INVALID_INPUT_LENGTH", "Funding Source must be 2 in length.", "Funding Source must be 2 in length."),
		INVALID_INPUT_VALUE_80001("INVALID_INPUT_VALUE", "File Date and Time must be in the past.", "File Date and Time provided in the File Header should be in the past."),
		INVALID_INPUT_VALUE_80002("INVALID_INPUT_VALUE", "File Date is not a valid date value.", "File Date must be between 30 days prior to the current UTC date and the current UTC date."),
		INVALID_INPUT_VALUE_80003("INVALID_INPUT_VALUE", "File Number is not unique. Possible duplicate file.", "The File Number and File Date combination specified in the File Header cannot match a file that has been previously submitted by the business partner and has a status of Accepted."),
		INVALID_INPUT_VALUE_80004("INVALID_INPUT_VALUE", "File Time is not a valid time value.", "File time must be a valid time"),
		INVALID_INPUT_VALUE_80005("INVALID_INPUT_VALUE", "Record Count in File Trailer does not match record count.", "The Record Count specified in the Trailer Record must equal the number of detail records provided."),
		INVALID_INPUT_VALUE_80100("INVALID_INPUT_VALUE", "Subscriber Type is invalid.", "Subscriber Type must be one of: PHONE_NUMBER EMAIL_ADDRESS"),
		INVALID_INPUT_VALUE_80101("INVALID_INPUT_VALUE", "Phone Number is invalid.", "Subscriber ID mobile number must contain valid country code."),
		INVALID_INPUT_VALUE_80102("INVALID_INPUT_VALUE", "Account Usage is invalid.", "Account usage must be one of: SENDING RECEIVING"),
		INVALID_INPUT_VALUE_80103("INVALID_INPUT_VALUE", "Account number is not a Card account.", "Account number must be a Card account"),
		INVALID_INPUT_VALUE_80104("INVALID_INPUT_VALUE", "Account number does not have a valid check digit.", "Account number must have a valid check digit"),
		INVALID_INPUT_VALUE_80105("INVALID_INPUT_VALUE", "Expiry date must be a valid date in the format YYYYMM.", "Expiry Date must be a valid date."),
		INVALID_INPUT_VALUE_80106("INVALID_INPUT_VALUE", "Country must be valid ISO 3166-1 Alpha-country code.", "Country must be a valid ISO 3166-1 Alpha-country code."),
		INVALID_INPUT_VALUE_80107("INVALID_INPUT_VALUE", "Date of Birth must be a valid date in the format YYYYMMDD.", "Date of Birth must be a valid date."),
		INVALID_INPUT_VALUE_80108("INVALID_INPUT_VALUE", "Date of Birth must be in the past.", "Date of Birth must be a date in the past."),
		INVALID_INPUT_VALUE_80109("INVALID_INPUT_VALUE", "Include Mapping Id or Subscriber Id/Subscriber Type/Acct Usage/Alias", "Mapping to be updated or deleted not identified."),
		INVALID_INPUT_VALUE_80110("INVALID_INPUT_VALUE", "Default mapping indicator must be 'T', 'F' or ' ' (a space).", "Default mapping indicator must be 'T', 'F' or ' ' (a space)."),
		INVALID_INPUT_VALUE_80111("INVALID_INPUT_VALUE", "Default mapping cannot be 'F' if there is no existing mapping for this subscriber id.", "Default mapping cannot be 'F'"),
		INVALID_INPUT_VALUE_80112("INVALID_INPUT_VALUE", "UNASSIGNED", "UNASSIGNED"),
		INVALID_INPUT_VALUE_80113("INVALID_INPUT_VALUE", "Middle name must be numeric or alpha", "Middle Name must be an alpha or numeric value"),
		INVALID_INPUT_VALUE_80114("INVALID_INPUT_VALUE", "Postal Code must be Alpha Numeric", "Postal Code must be Alpha Numeric"),
		INVALID_INPUT_VALUE_80115("INVALID_INPUT_VALUE", "Country subdivision must be an alpha character", "Country subdivision must be an alpha character"),
		INVALID_INPUT_VALUE_80116("INVALID_INPUT_VALUE", "Email address must contain '@'. Format x@y.", "Email address must contain '@'. Format x@y."),
		INVALID_INPUT_VALUE_80117("INVALID_INPUT_VALUE", "Account Number must be between 9 and 20 digits", "Account Number must be between 9 and 20 digits"),
		INVALID_INPUT_VALUE_80118("INVALID_INPUT_VALUE", "Service Manager Identification Number must be numeric", "Service Manager Identification Number must be numeric"),
		INVALID_INPUT_VALUE_80119("INVALID_INPUT_VALUE", "Service Manager Identification Number must be empty", "Service Manager Identification Number must be empty"),
		INVALID_INPUT_VALUE_80120("INVALID_INPUT_VALUE", "New Alias exists on another Account", "New Alias exists on another Account"),
		INVALID_INPUT_VALUE_80121("INVALID_INPUT_VALUE", "Alias must be Alpha Numeric", "Alias must be Alpha Numeric"),
		INVALID_INPUT_VALUE_80122("INVALID_INPUT_VALUE", "One Sending Account must be defined as the default", "One Sending Account must be defined as the default"),
		INVALID_INPUT_VALUE_80123("INVALID_INPUT_VALUE", "One Receiving Account must be defined as the default.", "One Receiving Account must be defined as the default."),
		INVALID_INPUT_VALUE_80124("INVALID_INPUT_VALUE", "Subscriber ID must be numeric when Subscriber Type is PHONE_NUMBER", "Subscriber ID must be numeric when Subscriber Type is PHONE_NUMBER"),
		INVALID_INPUT_VALUE_80125("INVALID_INPUT_VALUE", "Subscriber ID must be valid email address when Subscriber Type is EMAIL_ADDRESS", "Subscriber ID must be valid email address when Subscriber Type is EMAIL_ADDRESS"),
		INVALID_INPUT_VALUE_80126("INVALID_INPUT_VALUE", "Subscriber ID must be numeric when Subscriber Type is VIRTUAL_CARD_NUMBER", "Subscriber ID must be numeric when Subscriber Type is VIRTUAL_CARD_NUMBER"),
		INVALID_INPUT_VALUE_80127("INVALID_INPUT_VALUE", "Only one Alias is allowed per Account", "Only one Alias is allowed per Account"),
		INVALID_INPUT_VALUE_80128("INVALID_INPUT_VALUE", "An Alias can only be associated with one Account", "An Alias can only be associated with one Account"),
		INVALID_INPUT_VALUE_80129("INVALID_INPUT_VALUE", "Phone Number must be MSISDN format", "Phone Number must be MSISDN format"),
		INVALID_INPUT_VALUE_80130("INVALID_INPUT_VALUE", "Expiry Date cannot be expired for a Sending Account", "Expiry Date cannot be expired for a Sending Account"),
		INVALID_INPUT_VALUE_80131("INVALID_INPUT_VALUE", "Account is not  Eligible", "Account is not  Eligible"),
		INVALID_INPUT_VALUE_80132("INVALID_INPUT_VALUE", "Mapping ID does not match Subscriber ID", "Mapping ID does not match Subscriber ID"),
		INVALID_INPUT_VALUE_80133("INVALID_INPUT_VALUE", "Combination of data does not match an existing record", "Combination of data does not match an existing record"),
		INVALID_INPUT_VALUE_80134("INVALID_INPUT_VALUE", "Mapping not found for given data.", "Mapping not found for given data."),
		INVALID_INPUT_VALUE_80135("INVALID_INPUT_VALUE", "Subscriber Id not found for the given Subscriber Type.", "Subscriber to be deleted is not found."),
		INVALID_INPUT_VALUE_80137("INVALID_INPUT_VALUE", "Reserved field must be space filled.", "Reserved portion of file must be empty."),
		INVALID_INPUT_VALUE_80138("INVALID_INPUT_VALUE", "Expiry Date cannot be expired for Sending Account.", "Expiry Date cannot be expired for Sending Account."),
		INVALID_INPUT_VALUE_80139("INVALID_INPUT_VALUE", "Invalid Channel", "Invalid Channel"),
		INVALID_INPUT_VALUE_80140("INVALID_INPUT_VALUE", "Support UCAF is not allowed for the channel.", "Support UCAF is not allowed for the channel."),
		INVALID_INPUT_VALUE_80141("INVALID_INPUT_VALUE", "Funding UCAF is not allowed for the channel.", "Funding UCAF is not allowed for the channel."),
		INVALID_INPUT_VALUE_80142("INVALID_INPUT_VALUE", "Funding Card Assigned ID is not allowed for the channel.", "Funding Card Assigned ID is not allowed for the channel."),
		INVALID_INPUT_VALUE_80143("INVALID_INPUT_VALUE", "Amount Value must be greater than zero.", "Amount Value must be greater than zero."),
		INVALID_INPUT_VALUE_80144("INVALID_INPUT_VALUE", "Card is expired", "Card is expired"),
		INVALID_INPUT_VALUE_80145("INVALID_INPUT_VALUE", "Merchant Type must be 6532 or 6533", "Merchant Type must be 6532 or 6533"),
		INVALID_INPUT_VALUE_80146("INVALID_INPUT_VALUE", "Duplicate Request.", "Duplicate Request."),
		INVALID_INPUT_VALUE_80147("INVALID_INPUT_VALUE", "Duplicate Request.", "Duplicate Request."),
		INVALID_INPUT_VALUE_80148("INVALID_INPUT_VALUE", "Duplicate Request.", "Duplicate Request."),
		INVALID_INPUT_VALUE_80149("INVALID_INPUT_VALUE", "Duplicate Transaction Reference Number.", "Duplicate Transaction Reference Number."),
		INVALID_INPUT_VALUE_80150("INVALID_INPUT_VALUE", "Wallet and Transaction Reference Number are invalid.", "Wallet and Transaction Reference Number are invalid."),
		INVALID_INPUT_VALUE_80151("INVALID_INPUT_VALUE", "Reversal request type is invalid.", "Reversal request type is invalid."),
		INVALID_INPUT_VALUE_80152("INVALID_INPUT_VALUE", "Wallet and Transaction Reference Number are invalid.", "Wallet and Transaction Reference Number are invalid."),
		INVALID_INPUT_VALUE_80153("INVALID_INPUT_VALUE", "Reversal request type is invalid.", "Reversal request type is invalid."),
		INVALID_INPUT_VALUE_80154("INVALID_INPUT_VALUE", "Name and Address should not be provided for mapped account.", "Name and Address should not be provided for mapped account."),
		INVALID_INPUT_VALUE_80155("INVALID_INPUT_VALUE", "Processor ID must be numeric.", "Processor ID must be numeric."),
		INVALID_INPUT_VALUE_80156("INVALID_INPUT_VALUE", "Card Acceptor Country is not supported.", "Card Acceptor Country is not supported."),
		INVALID_INPUT_VALUE_80157("INVALID_INPUT_VALUE", "Amount Currency is not supported.", "Amount Currency is not supported."),
		INVALID_INPUT_VALUE_80158("INVALID_INPUT_VALUE", "Account number does not have a valid check digit.", "Account number does not have a valid check digit."),
		INVALID_INPUT_VALUE_80159("INVALID_INPUT_VALUE", "Subscriber Id not found for the given Subscriber Type.", "Subscriber Id not found for the given Subscriber Type."),
		INVALID_INPUT_VALUE_80160("INVALID_INPUT_VALUE", "One Sending Account must be defined as the default.", "One Sending Account must be defined as the default."),
		INVALID_INPUT_VALUE_80161("INVALID_INPUT_VALUE", "One Receiving Account must be defined as the default.", "One Receiving Account must be defined as the default."),
		INVALID_INPUT_VALUE_80162("INVALID_INPUT_VALUE", "An Alias can only be associated with one Account.", "An Alias can only be associated with one Account."),
		INVALID_INPUT_VALUE_80163("INVALID_INPUT_VALUE", "Default mapping cannot be 'F' if there is no existing mapping for this subscriber id.", "Default mapping cannot be 'F' if there is no existing mapping for this subscriber id."),
		INVALID_INPUT_VALUE_80164("INVALID_INPUT_VALUE", "At least one account number is required.", "At least one account number is required."),
		INVALID_INPUT_VALUE_80165("INVALID_INPUT_VALUE", "Invalid value", "Invalid value"),
		INVALID_INPUT_VALUE_80166("INVALID_INPUT_VALUE", "One Sending Account must be defined as the default and One Receiving Account must be defined as the default.", "One Sending Account must be defined as the default and One Receiving Account must be defined as the default."),
		INVALID_INPUT_VALUE_80167("INVALID_INPUT_VALUE", "Unauthorized to modify mapping", "Unauthorized to modify mapping."),
		INVALID_INPUT_VALUE_80175("INVALID_INPUT_VALUE", "Sender Address Line 1 must not be all blanks.", "Sender Address Line 1 must not be all blanks."),
		INVALID_INPUT_VALUE_80176("INVALID_INPUT_VALUE", "Sender Address Line 1 must not be all numeric.", "Sender Address Line 1 must not be all numeric."),
		INVALID_INPUT_VALUE_80177("INVALID_INPUT_VALUE", "Sender Address Country Subdivision must not be all blanks.", "Sender Address Country Subdivision must not be all blanks."),
		INVALID_INPUT_VALUE_80178("INVALID_INPUT_VALUE", "Sender Address Country Subdivision must not be all numeric.", "Sender Address Country Subdivision must not be all numeric."),
		INVALID_INPUT_VALUE_80179("INVALID_INPUT_VALUE", "Sender Address Country Subdivision Code must be valid for USA or CAN.", "Sender Address Country Subdivision Code must be valid for USA or CAN."),
		INVALID_INPUT_VALUE_80180("INVALID_INPUT_VALUE", "Sender Address Country Code is a blocked country code.", "Sender Address Country Code is a blocked country code."),
		INVALID_INPUT_VALUE_80181("INVALID_INPUT_VALUE", "Card Acceptor State/Province Code must be blank", "Card Acceptor State/Province Code must be blank"),
		INVALID_INPUT_VALUE_80182("INVALID_INPUT_VALUE", "Sender Address Country Code must be valid country code.", "Sender Address Country Code must be valid country code."),
		INVALID_INPUT_VALUE_80183("INVALID_INPUT_VALUE", "Funding Source 06 not valid when receiver card account number issued in USA.", "Funding Source 06 not valid when receiver card account number issued in USA."),
		INVALID_INPUT_VALUE_80184("INVALID_INPUT_VALUE", "Receiver Address Country Subdivision must be valid state code.", "Receiver Address Country Subdivision must be valid state code."),
		INVALID_INPUT_VALUE_80185("INVALID_INPUT_VALUE", "Receiver Address Country Code must be valid country code.", "Receiver Address Country Code must be valid country code."),
		INVALID_INPUT_VALUE_80186("INVALID_INPUT_VALUE", "Receiver Address Country Code is a blocked country code.", "Receiver Address Country Code is a blocked country code."),
		INVALID_INPUT_VALUE_80187("INVALID_INPUT_VALUE", "Funding Source must be valid value.", "Funding Source must be valid value."),
		MISSING_REQUIRED_INPUT_90100("MISSING_REQUIRED_INPUT", "Postal Code is required for Account Usage of SENDING.", "Postal Code"),
		MISSING_REQUIRED_INPUT_90101("MISSING_REQUIRED_INPUT", "Subscriber Type is required.", "Subscriber Type"),
		MISSING_REQUIRED_INPUT_90102("MISSING_REQUIRED_INPUT", "Originator Reference is required.", "Originator Reference is required"),
		MISSING_REQUIRED_INPUT_90103("MISSING_REQUIRED_INPUT", "Wallet is required.", "Wallet is required"),
		MISSING_REQUIRED_INPUT_90104("MISSING_REQUIRED_INPUT", "Subscriber ID is required.", "Subscriber ID is required"),
		MISSING_REQUIRED_INPUT_90105("MISSING_REQUIRED_INPUT", "Account Usage is required.", "Account Usage is required"),
		MISSING_REQUIRED_INPUT_90106("MISSING_REQUIRED_INPUT", "Alias is required.", "Card Alias is required"),
		MISSING_REQUIRED_INPUT_90107("MISSING_REQUIRED_INPUT", "Account Number is required.", "Account Number is required"),
		MISSING_REQUIRED_INPUT_90108("MISSING_REQUIRED_INPUT", "Expiry Date is required for Account Usage of SENDING.", "Expiry Date"),
		MISSING_REQUIRED_INPUT_90109("MISSING_REQUIRED_INPUT", "UNASSIGNED", "UNASSIGNED"),
		MISSING_REQUIRED_INPUT_90110("MISSING_REQUIRED_INPUT", "First Name is required if any other name or address field is populated", "First Name"),
		MISSING_REQUIRED_INPUT_90111("MISSING_REQUIRED_INPUT", "Last Name is required if any other name or address field is populated.", "Last Name"),
		MISSING_REQUIRED_INPUT_90112("MISSING_REQUIRED_INPUT", "Address Line 1 is required if any other name or address field is populated.", "Address Line 1"),
		MISSING_REQUIRED_INPUT_90113("MISSING_REQUIRED_INPUT", "City is required if any other name or address field is populated.", "City"),
		MISSING_REQUIRED_INPUT_90114("MISSING_REQUIRED_INPUT", "Country Subdivision is required if any other name or address field is populated.", "Country Subdivision"),
		MISSING_REQUIRED_INPUT_90115("MISSING_REQUIRED_INPUT", "Country is required if any other name or address field is populated.", "Country"),
		MISSING_REQUIRED_INPUT_90116("MISSING_REQUIRED_INPUT", "Record Type is required.", "Record Type specified in the record header is required"),
		MISSING_REQUIRED_INPUT_90117("MISSING_REQUIRED_INPUT", "Version is required.", "Version specified in the record header is required"),
		MISSING_REQUIRED_INPUT_90119("MISSING_REQUIRED_INPUT", "File Date is required.", "File Date specified in the record header is required"),
		MISSING_REQUIRED_INPUT_90120("MISSING_REQUIRED_INPUT", "File Time is required.", "File Time specified in the record header is required"),
		MISSING_REQUIRED_INPUT_90121("MISSING_REQUIRED_INPUT", "Cardholder Name must be valid.", "Cardholder Name must be valid."),
		MISSING_REQUIRED_INPUT_90122("MISSING_REQUIRED_INPUT", "Address is required.", "Address is required."),
		MISSING_REQUIRED_INPUT_90123("MISSING_REQUIRED_INPUT", "Support UCAF is required.", "Support UCAF is required."),
		MISSING_REQUIRED_INPUT_90124("MISSING_REQUIRED_INPUT", "Card Acceptor State/Province Code is required", "Card Acceptor State/Province Code is required"),
		MISSING_REQUIRED_INPUT_90125("MISSING_REQUIRED_INPUT", "Card Acceptor State/Province Code must be a valid code.", "Card Acceptor State/Province Code must be a valid code."),
		MISSING_REQUIRED_INPUT_90126("MISSING_REQUIRED_INPUT", "Sender Name is required.", "Sender Name is required."),
		MISSING_REQUIRED_INPUT_90127("MISSING_REQUIRED_INPUT", "Receiver Name is required.", "Receiver Name is required."),
		MISSING_REQUIRED_INPUT_90128("MISSING_REQUIRED_INPUT", "Transaction Reference is required.", "Transaction Reference is required."),
		MISSING_REQUIRED_INPUT_90129("MISSING_REQUIRED_INPUT", "Reversal Reason is required.", "Reversal Reason is required."),
		MISSING_REQUIRED_INPUT_90130("MISSING_REQUIRED_INPUT", "Processor ID required.", "Processor ID required."),
		MISSING_REQUIRED_INPUT_90131("MISSING_REQUIRED_INPUT", "Routing and Transit Number is required.", "Routing and Transit Number is required."),
		MISSING_REQUIRED_INPUT_90132("MISSING_REQUIRED_INPUT", "Local Date is required.", "Local Date is required."),
		MISSING_REQUIRED_INPUT_90133("MISSING_REQUIRED_INPUT", "Local Time is required.", "Local Time is required."),
		MISSING_REQUIRED_INPUT_90134("MISSING_REQUIRED_INPUT", "Default Indicator must be 1 character in length.", "Default Indicator must be 1 character in length."),
		MISSING_REQUIRED_INPUT_90135("MISSING_REQUIRED_INPUT", "Card Acceptor is required.", "Card Acceptor is required."),
		MISSING_REQUIRED_INPUT_90136("MISSING_REQUIRED_INPUT", "Card Acceptor Name is required", "Card Acceptor Name is required"),
		MISSING_REQUIRED_INPUT_90137("MISSING_REQUIRED_INPUT", "Client Code is required.", "Client Code is required."),
		MISSING_REQUIRED_INPUT_90138("MISSING_REQUIRED_INPUT", "Merchant Type is required.", "Merchant Type is required."),
		MISSING_REQUIRED_INPUT_90139("MISSING_REQUIRED_INPUT", "Channel is required.", "Channel is required."),
		MISSING_REQUIRED_INPUT_90140("MISSING_REQUIRED_INPUT", "Card Acceptor City is required.", "Card Acceptor City is required."),
		MISSING_REQUIRED_INPUT_90141("MISSING_REQUIRED_INPUT", "Card Acceptor Country is required.", "Card Acceptor Country is required."),
		MISSING_REQUIRED_INPUT_90142("MISSING_REQUIRED_INPUT", "Card Number is required.", "Card Number is required."),
		MISSING_REQUIRED_INPUT_90143("MISSING_REQUIRED_INPUT", "Amount Value is required.", "Amount Value is required."),
		MISSING_REQUIRED_INPUT_90144("MISSING_REQUIRED_INPUT", "Amount Currency is required.", "Amount Currency is required."),
		MISSING_REQUIRED_INPUT_90145("MISSING_REQUIRED_INPUT", "Receiving Subscriber Alias is required.", "Receiving Subscriber Alias is required."),
		MISSING_REQUIRED_INPUT_90146("MISSING_REQUIRED_INPUT", "Receiving Subscriber Type is required.", "Receiving Subscriber Type is required."),
		MISSING_REQUIRED_INPUT_90147("MISSING_REQUIRED_INPUT", "Receiving Subscriber ID is required.", "Receiving Subscriber ID is required."),
		MISSING_REQUIRED_INPUT_90148("MISSING_REQUIRED_INPUT", "Receiving Info is required.", "Receiving Info is required."),
		MISSING_REQUIRED_INPUT_90149("MISSING_REQUIRED_INPUT", "Receiving Card Number is required.", "Receiving Card Number is required."),
		MISSING_REQUIRED_INPUT_90150("MISSING_REQUIRED_INPUT", "Receiver Address is required.", "Receiver Address is required."),
		MISSING_REQUIRED_INPUT_90151("MISSING_REQUIRED_INPUT", "Sender Address is required", "Sender Address is required"),
		MISSING_REQUIRED_INPUT_90152("MISSING_REQUIRED_INPUT", "Funding Subscriber Alias is required.", "Funding Subscriber Alias is required."),
		MISSING_REQUIRED_INPUT_90153("MISSING_REQUIRED_INPUT", "Funding Subscriber Type is required.", "Funding Subscriber Type is required."),
		MISSING_REQUIRED_INPUT_90154("MISSING_REQUIRED_INPUT", "Funding Subscriber ID is required.", "Funding Subscriber ID is required."),
		MISSING_REQUIRED_INPUT_90155("MISSING_REQUIRED_INPUT", "Expiry Year is required.", "Expiry Year is required."),
		MISSING_REQUIRED_INPUT_90156("MISSING_REQUIRED_INPUT", "Expiry Month is required.", "Expiry Month is required."),
		MISSING_REQUIRED_INPUT_90157("MISSING_REQUIRED_INPUT", "Funding Card Number is required.", "Funding Card Number is required."),
		MISSING_REQUIRED_INPUT_90158("MISSING_REQUIRED_INPUT", "Funding Info is required.", "Funding Info is required."),
		MISSING_REQUIRED_INPUT_90159("MISSING_REQUIRED_INPUT", "Client Code is required.", "Client Code is required."),
		MISSING_REQUIRED_INPUT_90160("MISSING_REQUIRED_INPUT", "Default Indicator is required.", "Default Indicator is required."),
		MISSING_REQUIRED_INPUT_90162("MISSING_REQUIRED_INPUT", "Cardholder Name is required", "Cardholder Name is required"),
		INVALID_INPUT_VALUE_90173("INVALID_INPUT_VALUE", "Payment Type is Invalid.", "Payment Type is Invalid."),
		MISSING_REQUIRED_INPUT_90183("MISSING_REQUIRED_INPUT", "Transaction Description is required.", "Transaction Description is required."),
		MISSING_REQUIRED_INPUT_90190("MISSING_REQUIRED_INPUT", "Sender Address Line 1 is required.", "Sender Address Line 1 is required."),
		MISSING_REQUIRED_INPUT_90191("MISSING_REQUIRED_INPUT", "Sender Address Subdivision is required", "Sender Address Subdivision is required"),
		MISSING_REQUIRED_INPUT_90192("MISSING_REQUIRED_INPUT", "Sender Address Country Code is required", "Sender Address Country Code is required"),
		MISSING_REQUIRED_INPUT_90193("MISSING_REQUIRED_INPUT", "Sender Address Country Subdivision is required if Sender Address Country is USA or CAN.", "Sender Address Country Subdivision is required if Sender Address Country is USA or CAN."),
		MISSING_REQUIRED_INPUT_90196("MISSING_REQUIRED_INPUT", "Receiver Address Country Subdivision is required if Receiver Address Country is USA or CAN.", "Receiver Address Country Subdivision is required if Receiver Address Country is USA or CAN."),
		MISSING_REQUIRED_INPUT_90197("MISSING_REQUIRED_INPUT", "Funding Source is required.", "Funding Source is required."),
		MISSING_REQUIRED_INPUT_90198("MISSING_REQUIRED_INPUT", "Sender FundingCard AccountNumber is required.", "Sender FundingCard AccountNumber is required."),
		MISSING_REQUIRED_INPUT_90199("MISSING_REQUIRED_INPUT", "Sender First Name is required.", "Sender First Name is required."),
		MISSING_REQUIRED_INPUT_90200("MISSING_REQUIRED_INPUT", "Sender Last Name is required.", "Sender Last Name is required."),
		MISSING_REQUIRED_INPUT_90201("MISSING_REQUIRED_INPUT", "SenderName parent tag is required.", "SenderName parent tag is required."),
		MISSING_REQUIRED_INPUT_90202("MISSING_REQUIRED_INPUT", "ReceiverName parent tag is required.", "ReceiverName parent tag is required."),
		MISSING_REQUIRED_INPUT_90203("MISSING_REQUIRED_INPUT", "FundingCard parent tag is required.", "FundingCard parent tag is required."),
		MISSING_REQUIRED_INPUT_90204("MISSING_REQUIRED_INPUT", "Receiver First Name is required.", "Receiver First Name is required."),
		MISSING_REQUIRED_INPUT_90205("MISSING_REQUIRED_INPUT", "Receiver Last Name is required.", "Receiver Last Name is required."),
		SERVICE_ERROR_110001("SERVICE_ERROR", "Account mapping already exists", "Create mapping failed because mapping already exists"),
		SERVICE_ERROR_110002("SERVICE_ERROR", "Transaction to be reversed currently in progress.", "Transaction to be reversed currently in progress."),
		SERVICE_ERROR_110003("SERVICE_ERROR", "The reversal window has passed.", "The reversal window has passed."),
		SERVICE_ERROR_110004("SERVICE_ERROR", "Transaction to be reversed currently in progress", "Transaction to be reversed currently in progress"),
		SERVICE_ERROR_110005("SERVICE_ERROR", "Transaction to be reversed currently in progress.", "Transaction to be reversed currently in progress."),
		SERVICE_ERROR_110006("SERVICE_ERROR", "Transaction to be reversed currently in progress.", "Transaction to be reversed currently in progress."),
		SERVICE_ERROR_110007("SERVICE_ERROR", "Failed to process reversal request.", "Failed to process reversal request."),
		SERVICE_ERROR_110008("SERVICE_ERROR", "Failed to create the reversal response for reversed transaction.", "Failed to create the reversal response for reversed transaction."),
		SERVICE_ERROR_110009("SERVICE_ERROR", "Unknown transaction request type", "Unknown transaction request type"),
		SERVICE_ERROR_110010("SERVICE_ERROR", "Failure to check eligibility of account", "Failure to check eligibility of account"),
		SERVICE_ERROR_110011("SERVICE_ERROR", "Both Sending Account and Receiving Account are not eligible for Transfer.", "Both Sending Account and Receiving Account are not eligible for Transfer."),
		SERVICE_ERROR_110012("SERVICE_ERROR", "Account is not  Eligible.", "Failure to check eligibility of account"),
		SERVICE_ERROR_110013("SERVICE_ERROR", "Account is not  Eligible.", "Account is not  Eligible."),
		SERVICE_ERROR_110014("SERVICE_ERROR", "Failed to get mapped account information.", "Failed to get mapped account information."),
		SERVICE_ERROR_110015("SERVICE_ERROR", "Account is not  Eligible.", "Account is not  Eligible."),
		SERVICE_ERROR_110016("SERVICE_ERROR", "Account mapping already exists.", "Account mapping already exists."),
		SERVICE_ERROR_110017("SERVICE_ERROR", "Subscriber ID already used.", "Subscriber ID already used."),
		SERVICE_ERROR_110018("SERVICE_ERROR", "Failed to create request.", "Failed to create request."),
		SERVICE_ERROR_110019("SERVICE_ERROR", "Funding account not found.", "Funding account not found."),
		SERVICE_ERROR_110020("SERVICE_ERROR", "Receiving account not found.", "Receiving account not found."),
		SERVICE_ERROR_110021("SERVICE_ERROR", "Only one Alias is allowed per Account.", "Only one Alias is allowed per Account."),
		SERVICE_ERROR_110022("SERVICE_ERROR", "Unknown transaction request type", "Unknown transaction request type"),
		SYSTEM_ERROR_120001("SYSTEM_ERROR", "Failed to get account information.", "Failed to get account information."),
		SYSTEM_ERROR_120002("SYSTEM_ERROR", "Unable to process account mapping request.", "Unable to process account mapping request."),
		SYSTEM_ERROR_120003("SYSTEM_ERROR", "Failed to delete account mapping.", "Failed to delete account mapping."),
		SYSTEM_ERROR_120004("SYSTEM_ERROR", "Failed to delete subscriber.", "Failed to delete subscriber."),
		SYSTEM_ERROR_120005("SYSTEM_ERROR", "Failed to update account mapping.", "Failed to update account mapping."),
		SYSTEM_ERROR_120006("SYSTEM_ERROR", "Failed to process request.", "Failed to process request."),
		SYSTEM_ERROR_120007("SYSTEM_ERROR", "Failed to process request:", ""),
		SYSTEM_ERROR_120008("SYSTEM_ERROR", "Failed to perform security check.", "Failed to perform security check."),
		SYSTEM_ERROR_120009("SYSTEM_ERROR", "SERVICE_ERROR", "SERVICE_ERROR"),
		SYSTEM_ERROR_120010("SYSTEM_ERROR", "Failed to create request.", "Failed to create request."),
		SYSTEM_ERROR_120011("SYSTEM_ERROR", "system error", "system error"),
		SYSTEM_ERROR_120012("SYSTEM_ERROR", "Failed to submit transaction to the payment network.", "Failed to submit transaction to the payment network."),
		SYSTEM_ERROR_120013("SYSTEM_ERROR", "Failure to determine PAN eligibility.", "Failure to determine PAN eligibility."),
		SYSTEM_ERROR_120014("SYSTEM_ERROR", "New Alias exists on another Account", "New Alias exists on another Account"),
		SYSTEM_ERROR_120016("SYSTEM_ERROR", "PAN is not eligible as Wallet is blocked", "Wallet is not Transfer eligible"),
		SYSTEM_ERROR_120017("SYSTEM_ERROR", "PAN is not eligible as account range is blocked", "Account is not Transfer eligible"),
		SYSTEM_ERROR_120018("SYSTEM_ERROR", "PAN is not eligible as country code is blocked", "Country code is not Transfer eligible"),
		SYSTEM_ERROR_120019("SYSTEM_ERROR", "PAN is not within an eligible account range", "Account range is not Transfer eligible"),
		INTERNAL_SYSTEM_ERROR_999999("INTERNAL_SYSTEM_ERROR", "Internal System Error", "System Error");


		
		private String message;
		@SuppressWarnings("unused")
		private String responseCode;
		@SuppressWarnings("unused")
		private String description;

		private WalletError(String message) {
			this.message = message;
		}
		
		private WalletError (String responseCode, 
				String description, String message) {
			this.responseCode = responseCode;
			this.description = description;
			this.message = message;
			
		}
	}

}